# Generated by Django 5.2.6 on 2025-10-15 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_remove_project_created_by_remove_project_developer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='documents_uploaded',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_completed',
        ),
    ]
