# Generated by Django 5.2.6 on 2025-09-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity',
            name='has_air_conditioning',
        ),
        migrations.RemoveField(
            model_name='amenity',
            name='has_balcony',
        ),
        migrations.RemoveField(
            model_name='amenity',
            name='has_elevator',
        ),
        migrations.RemoveField(
            model_name='amenity',
            name='has_garden',
        ),
        migrations.RemoveField(
            model_name='amenity',
            name='has_gym',
        ),
        migrations.RemoveField(
            model_name='amenity',
            name='has_power_backup',
        ),
        migrations.RemoveField(
            model_name='amenity',
            name='has_security',
        ),
        migrations.RemoveField(
            model_name='amenity',
            name='has_swimming_pool',
        ),
        migrations.RemoveField(
            model_name='amenity',
            name='pet_friendly',
        ),
        migrations.AddField(
            model_name='amenity',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='amenity',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='property',
            name='amenities',
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='properties', to='property.amenity'),
        ),
    ]
