# Generated by Django 5.2.6 on 2025-09-25 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_remove_amenity_has_air_conditioning_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Amenity', 'verbose_name_plural': 'Amenities'},
        ),
        migrations.AddField(
            model_name='amenity',
            name='category',
            field=models.CharField(choices=[('indoor', 'Indoor Amenity'), ('outdoor', 'Outdoor Amenity'), ('building', 'Building Amenity'), ('security', 'Security Feature'), ('utilities', 'Utilities'), ('recreational', 'Recreational'), ('parking', 'Parking Related'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='amenity',
            name='icon',
            field=models.CharField(blank=True, help_text='Icon class name for UI display', max_length=50),
        ),
        migrations.AddField(
            model_name='amenity',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='balconies',
            field=models.PositiveIntegerField(default=0, help_text='Number of Balconies'),
        ),
        migrations.AddField(
            model_name='property',
            name='built_up_area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Built-up Area (sq.ft.)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='facing_direction',
            field=models.CharField(blank=True, help_text='Property Facing Direction', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='land_type_zone',
            field=models.CharField(blank=True, help_text='Land Type / Zone', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='lease_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Lease Duration (months)', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='lease_total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Lease total amount', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='monthly_rent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly Rent', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='plot_area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Plot Area (sq.ft.)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='rent_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration (months) for rent', null=True),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='PropertyVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video', models.FileField(upload_to='property_videos/%Y/%m/%d/')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='property_video_thumbnails/%Y/%m/%d/')),
                ('duration', models.DurationField(blank=True, help_text='Video duration', null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='property.property')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property Video',
                'verbose_name_plural': 'Property Videos',
                'ordering': ['order', 'created_at'],
                'unique_together': {('property', 'order')},
            },
        ),
        migrations.CreateModel(
            name='VirtualTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('tour_url', models.URLField(help_text='Third-party virtual tour link')),
                ('tour_type', models.CharField(choices=[('360_view', '360 Degree View'), ('virtual_walkthrough', 'Virtual Walkthrough'), ('interactive_tour', 'Interactive Tour'), ('matterport', 'Matterport Tour'), ('google_tour', 'Google Street View Tour'), ('zillow_3d', 'Zillow 3D Tour'), ('other', 'Other')], default='360_view', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='virtual_tour_thumbnails/%Y/%m/%d/')),
                ('provider', models.CharField(blank=True, help_text='e.g., Matterport, TourWrist, etc.', max_length=100)),
                ('embed_code', models.TextField(blank=True, help_text='Embed HTML code if available')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_tours', to='property.property')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Virtual Tour',
                'verbose_name_plural': 'Virtual Tours',
                'ordering': ['order', 'created_at'],
                'unique_together': {('property', 'order')},
            },
        ),
    ]
