# Generated by Django 5.2.6 on 2025-09-25 05:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_amenity_options_amenity_category_amenity_icon_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='owner',
        ),
        migrations.AddField(
            model_name='property',
            name='developers',
            field=models.ManyToManyField(related_name='properties', to=settings.AUTH_USER_MODEL),
        ),
    ]
