# Generated by Django 5.2.6 on 2025-10-07 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_remove_property_owner_property_developers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualtour',
            name='title',
        ),
    ]
