# Generated by Django 5.2.6 on 2025-10-13 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_remove_virtualtour_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('alternate_phone', models.CharField(blank=True, max_length=20)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum budget', max_digits=15, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum budget', max_digits=15, null=True)),
                ('preferred_location', models.CharField(blank=True, help_text='Preferred location/area', max_length=255)),
                ('requirements', models.TextField(blank=True, help_text='Specific requirements or notes')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('proposal_sent', 'Proposal Sent'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('lead_source', models.CharField(choices=[('website', 'Website'), ('referral', 'Referral'), ('social_media', 'Social Media'), ('advertisement', 'Advertisement'), ('cold_call', 'Cold Call'), ('email_campaign', 'Email Campaign'), ('walk_in', 'Walk In'), ('other', 'Other')], default='website', max_length=20)),
                ('lead_source_details', models.CharField(blank=True, help_text='Additional details about the lead source', max_length=255)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('next_follow_up', models.DateTimeField(blank=True, null=True)),
                ('last_contacted', models.DateTimeField(blank=True, null=True)),
                ('contact_count', models.PositiveIntegerField(default=0)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, default='India', max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('newsletter_subscribed', models.BooleanField(default=False)),
                ('sms_marketing', models.BooleanField(default=False)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_assigned_by_me', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('interested_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='property.property')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'priority'], name='property_le_status_b4fe59_idx'), models.Index(fields=['interested_property', 'status'], name='property_le_interes_92f71f_idx'), models.Index(fields=['assigned_to', 'status'], name='property_le_assigne_04ef1c_idx'), models.Index(fields=['email'], name='property_le_email_e9ae31_idx'), models.Index(fields=['phone'], name='property_le_phone_13453e_idx'), models.Index(fields=['created_at'], name='property_le_created_58ccf5_idx')],
            },
        ),
    ]
