# Generated by Django 5.2.6 on 2025-10-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_remove_project_developer_project_developers'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='highlighted_features',
            field=models.TextField(blank=True, help_text='Comma-separated highlighted features'),
        ),
    ]
