# Generated by Django 5.2.6 on 2025-10-13 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_property_highlighted_features'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='highlighted_features',
            new_name='highlightes',
        ),
    ]
