# Generated by Django 5.2.6 on 2025-10-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_floorplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floorplan',
            name='rera_id',
        ),
        migrations.AddField(
            model_name='property',
            name='rera_id',
            field=models.CharField(blank=True, help_text='RERA Registration ID', max_length=50, null=True),
        ),
    ]
