# Generated by Django 5.2.6 on 2025-10-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_alter_lead_unique_together_leadlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorplan',
            name='floor_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
