# Generated by Django 5.2.6 on 2025-10-17 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_alter_project_developers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_approved',
        ),
    ]
