# Generated by Django 5.2.6 on 2025-10-17 09:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_remove_project_approved_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='propertywishlistitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='propertywishlistitem',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='propertywishlistitem',
            name='property',
        ),
        migrations.RemoveField(
            model_name='propertywishlistitem',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='propertywishlistitem',
            name='wishlist',
        ),
        migrations.AlterUniqueTogether(
            name='propertywishlist',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='propertywishlist',
            name='properties',
            field=models.ManyToManyField(to='property.property'),
        ),
        migrations.AddConstraint(
            model_name='propertywishlist',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_user_wishlist_name'),
        ),
        migrations.DeleteModel(
            name='PropertyWishlistItem',
        ),
    ]
