# Generated by Django 5.2.6 on 2025-10-17 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_propertywishlistitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyWishlistItem',
        ),
    ]
