# Generated by Django 5.2.6 on 2025-10-17 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_delete_propertywishlistitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertywishlist',
            name='user',
        ),
    ]
