# Generated by Django 5.2.6 on 2025-10-17 11:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0021_remove_propertywishlist_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='propertywishlist',
            name='unique_user_wishlist_name',
        ),
        migrations.AlterField(
            model_name='propertywishlist',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='propertywishlist',
            constraint=models.UniqueConstraint(fields=('created_by', 'name'), name='unique_user_wishlist_name'),
        ),
    ]
