# Generated by Django 5.2.6 on 2025-10-17 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0024_alter_propertywishlist_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='propertywishlist',
            name='unique_user_wishlist_name',
        ),
    ]
