# Generated by Django 5.2.6 on 2025-10-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0026_alter_propertywishlist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertywishlist',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
