# Generated by Django 5.2.6 on 2025-10-18 04:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0027_alter_propertywishlist_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertywishlist',
            name='properties',
            field=models.ManyToManyField(blank=True, related_name='wishlists', to='property.property'),
        ),
        migrations.AddConstraint(
            model_name='propertywishlist',
            constraint=models.UniqueConstraint(fields=('created_by',), name='unique_wishlist_per_user'),
        ),
    ]
