# Generated by Django 5.2.6 on 2025-10-24 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0028_alter_propertywishlist_properties_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='property',
            name='property_pr_price_b1d594_idx',
        ),
        migrations.RemoveField(
            model_name='property',
            name='price',
        ),
        migrations.AddField(
            model_name='property',
            name='maximum_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum price for properties with price range', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='minimum_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum price for properties with price range', max_digits=15, null=True),
        ),
    ]
